### ISSUE TITLE
Screen locks automatically after 1 min

### ISSUE THREAD

**Issue by mgraesslin** [blue-systems/plasma-5.3#83]
1. Start latest iso (March 13th)
2. Wait 1 min

Observe: screen locks

Expected behavior:
screen doesn't lock (that was the behavior on last weeks iso) or locks after 5 min (which is upstream default).

**Comment by davidedmundson** [comment]
this is a combo of me changing the way the config is stored (sorry!) and Kubuntu doing something funky.

Due to a change (for Plasma 5.3)
the config Timeout was split into
Autolock (true|false)
and Timeout(1-99)

I carefully updated the defaults, and a script updates all user's configs on load. all is nice.
However, Kubuntu is providing their own system wide default config

 /usr/share/kubuntu-default-settings/kf5-settings/kscreenlockerrc
with Timeout=0 in there.

kconfigxt then is "clever" and manipulates that to 1.

Best fix will be if we can change the kubuntu-settings for the ISO. 

Kubuntu people, where would I find this?

**Comment by mck182** [comment]
I'm not sure how exactly is the timeout config handled now after the changes but I still get my system (not iso) locked even though I've disabled the checkbox, here's my config:

[$Version]
update_info=kscreenlocker.upd:0.1-autolock

[Daemon]
Autolock=false
LockOnResume=false
Timeout=20

[Greeter]
Theme=org.kde.breeze.desktop

**Comment by apachelogger** [comment]
should be fixed next week
http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/casper/vivid/revision/1165

**Comment by star-buck** [comment]
dont forget to label "solved, needs packaging"
