### ISSUE TITLE
[logout]: black screen, hangs without falling back to sddm

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#85]
possible upstream report:
https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/1407152
https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1436715

**Comment by star-buck** [comment]
still there as of kci 20150327, I tested with having firefox window still open, then logout, screen goes black for a second, then shows firefox window content without any other plasma components like panel, etc. only mouse cursor visible which can move, otherwise desktop seems frozen (no ALT-SPACE possible).

**Comment by star-buck** [comment]
still happening kci20150403

**Comment by davidedmundson** [comment]
yeah, it's not just Kubuntu. I've got some other reports here https://github.com/sddm/sddm/issues/385.
 I've been on it for the past 2 days but I'm rather stumped.

**Comment by davidedmundson** [comment]
After 3 solid days, I've found it!
And for the 5th time in a row, the bug is caused by Kubuntu's replacement PAM files. Though in fairness, this time is probably the fault of someone else moving something in Vivid, and in a super surprise twist the fault of Gnome.

Kubuntu people packaged the sddm PAM file to include pam_gnome_keyring.
common_password already included pam_gnome_keyring.
sddm's pam file includes common_password.

The end result is session pam_gnome_keyring is included twice.

The first one sets up a signal handler, starts gnome-keyring and all is well.
The second one sets up a signal handler, does nothing, then intercepts all of my SIGCHLD signals that I need in sddm-helper to know when our session ends.
Our QProcess object never gets told the child exited so never wakes up and the session (startkde, openbox whatever) is in a defunct state waiting for us to read the exit state.

In upstream SDDM our sddm pam file doesn't include gnome-keyring, we just source system-login so it's not a problem there.

Fix: remove both lines referencing gnome_keyring in the sddm.pam file in the packaging patches.
sddm-autologin should be left as-is.

**Comment by star-buck** [comment]
does it also fix these upstream cases:
https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1436715

**Comment by davidedmundson** [comment]
I don't think so. That message is long after SDDM has finished doing anything useful.
Also it appears in that report to affect vanilla Ubuntu which wouldn't by running SDDM at all.

**Comment by star-buck** [comment]
okay, i just thought I sometimes experienced the freeze not only with logout, but also when shutdown or reboot.

**Comment by davidedmundson** [comment]
Heh.
I just patched gnome-keyring to make sure it didn't leakily leave signal handlers on error.
It's been fixed already will be in 3.15.92

upstream report, it broke mdm too
    https://bugzilla.gnome.org/show_bug.cgi?id=745673

**Comment by davidedmundson** [comment]
IMHO waiting for that patch to hit Vivid is probably the better fix.

**Comment by jriddell** [comment]
https://launchpad.net/ubuntu/+source/gnome-keyring 3.16 packaged and in with the fix

**Comment by star-buck** [comment]
works.
