### ISSUE TITLE
[koko]: when copying some images to ~home directory, baloo crashes, koko shows no images

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#88]
![baloo](https://cloud.githubusercontent.com/assets/840070/6655433/e0142466-cb01-11e4-99d1-fcf7bbe89b9b.png)

**Comment by star-buck** [comment]
can anyone confirm this or please make a screencast showing how koko works in kci otherwise, with adding pictures and folders?
@vHanda :
If not working in kci, please make a somewhat lengthy screencast, showing how this is supposed to work on your computer with starting empty, then adding pictures, adding folders with new pictures, etc. before and after, thank you.

**Comment by vHanda** [comment]
Hey Clemens.

I tested it out today, and apart from some minor issues (fixed) it is working correctly. I even added live updates (so one doesn't need to restart the application). Could you please see if it works for you?

Please note that Koko will not work on the live cd unless you **install the live cd**. The livecd uses a file system (overlayfs) which is buggy. Fixing this is not trivial as it means patching the kernel.

Also, since many people do not like it picking up images from the entire system, I've for now restricted the images to your "Pictures" folder only.

**Comment by star-buck** [comment]
@vHanda :
Can you please make a screencast as described above?
I tried koko always on an installed system, and it fails, so please do the screencast as an example how its supposed to work, thanks,

**Comment by vHanda** [comment]
I made a very simple video -
* https://www.youtube.com/watch?v=oVzPZlrdFS4
* Same video with youtube music - https://www.youtube.com/watch?v=pKd2Etsfe5M

**Comment by star-buck** [comment]
Thanks for the vid, looks promising.
Now I also got it running on the latest kci myself, will report back when done some more testing.
