### ISSUE TITLE
[black icons]: some icons in menu seem missing, appear as black squares

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#95]
![black-icons](https://cloud.githubusercontent.com/assets/840070/6885416/0f761cea-d620-11e4-87d4-1a65316a97d3.png)

**Comment by eikehein** [comment]
mck182, iirc you had the upstream QTBUG number for that ...?

**Comment by mck182** [comment]
No, unfortunately; I reported it to you on irc and someone else said something else, possibly with a QTBUG, I really don't remember :)

**Comment by eikehein** [comment]
Could also be a bug in QIconItem when it gets an empty QIcon ...

**Comment by eikehein** [comment]
Looks like it's a regression caused by a commit from ogoffart to kiconthemes: https://bugs.kde.org/show_bug.cgi?id=345740

**Comment by eikehein** [comment]
It turns out that the fallback icons apparently only worked accidentally in the library prior to ogoffart's commit, and the commit addresses that. So this adds explicit fallbacks to Kicker now:

https://commits.kde.org/plasma-desktop/aa08cd42a470af7a10f34cc9dbe7aefd0057bb35

Independent of that QIconItem should be fixed not to show a black square on an empty texture, however.

**Comment by star-buck** [comment]
seems fixed?
