### ISSUE TITLE
[kicker menu]: wrong names

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#97]
Menu entry names from one category to still show up in next category:
https://www.dropbox.com/s/18cml4u6n878xpq/kicker-names.mkv?dl=0

**Comment by eikehein** [comment]
Currently no idea about this - the model emits a single dataChanged() for the entire row, so there's nothing in Kicker code that would account for the icon updating but not the text. Until I can reproduce it I can't figure out where in the stack the bug might be.

**Comment by star-buck** [comment]
tough to get this reliably work... i changed themeing to oxygen, now seems to no longer work, but could be for various reasons.... though i know to remember it was reported to happen also elsewhere (manjaro forum), and I certainly recall it randomly happen to me in the past .

**Comment by star-buck** [comment]
Reliably reproducable in latest kci (so try it there to analyze why it happens):
https://www.dropbox.com/s/esuvca95b2o1se6/kicker-wrong-names.mkv?dl=0
as soon as one has 2 items in "Recent Apps", one can provoke the names of the 2 items to show up on the underlying menu entries.

**Comment by eikehein** [comment]
Unfortunately I can't reproduce it on the KCI ISO in a VM. It's interesting that in your video it fixes itself as soon as the cursor enters ...

**Comment by eikehein** [comment]
Clemens, could you add which GPU and driver your test machine has?

**Comment by eikehein** [comment]
Anyway, I audited+debugged the model again today including with GammaRay which d_ed recommended, and it's behaving like it should. Plus in the video, the icons update but the text labels don't, even though the model doesn't emit any role-specific data changes. I'm feeling more and more like this is probably a GPU/driver-specific rendering problem, since I can't reproduce it on the ISO in A VM or on my nVidia workstation. I'm guessing it's Qt+Mesa again ...
